### ISSUE TITLE
Make install and sudo make install

### ISSUE THREAD

**Issue by KatStark** [CertiCoq/certicoq#12]
Hi all, 

trying to install CertiCoq me + others spent time with the fact that it is required to have make install and not sudo make install (as everything is installed via Opam).
Maybe one could either adapt the make files or mention this in the instructions? -- Thanks!

Kathrin

**Comment by yforster** [comment]
Can you quickly post the two screenshots with the errors here? That way it's probably easier to figure out what the issues were in a couple of weeks

**Comment by KatStark** [comment]
Sure, here they are:

![screenshot-sudo-2](https://user-images.githubusercontent.com/28627755/71906842-e352b780-3138-11ea-93d3-93b4b392ad37.jpeg)
![Screenshot-sudo](https://user-images.githubusercontent.com/28627755/71906843-e352b780-3138-11ea-810b-537cc25f030f.jpeg)
