### ISSUE TITLE
ExtLib temporarily not tracking this project

### ISSUE THREAD

**Issue by liyishuai** [CertiCoq/certicoq#61]
coq-ext-lib normally checks all dependants in its CI, but coq-certicoq takes too long to build, and exhausts the time budget.
coq-community/coq-ext-lib#135 skips the compatibility checking with CertiCoq.
Before we figure out how to add it back (e.g. by switching to GitHub Actions), please be aware of potential incompatibilities with newer versions of ExtLib, and submit complaints via GitHub Issues.

**Comment by mattam82** [comment]
Noted!
