### ISSUE TITLE
function tags in LambdaANF are not unique

### ISSUE THREAD

**Issue by womeier** [CertiCoq/certicoq#63]
Some background:

I'm working on a backend to WebAssembly (together with Jean Pichon-Pharabod and Bas Spitters).
When translating indirect function calls I'd like to use the function tags of LambdaANF function definitions to distinguish functions.

From the comment [here](https://github.com/CertiCoq/certicoq/blob/87dff37df58f426fa0c267ac45908f0ce40e7b17/theories/LambdaANF/cps.v#LL23C26-L23C29) I assumed that they would be unique, but they are not, e.g. [vs_easy from the benchmarks](https://gist.github.com/womeier/7d6e1ffd282e0a4b971ef7f7d8c251a8).

Am I missing something?

For the C-backend, that is not an issue since indirect calls work by passing the function pointer directly. However, WebAssembly doesn't have function pointers (that may be the case for other potential target languages as well.)

**Comment by andrew-appel** [comment]
The purpose of function tags, if I recall correctly, is the partition all the functions by their calling conventions.  In particular, if two functions could flow to the same (function-valued) variable, then they must have the same tag.

**Comment by womeier** [comment]
that makes more sense. thanks!
