### ISSUE TITLE
Bugs in implementation of primitive operations

### ISSUE THREAD

**Issue by mkarup** [CertiCoq/certicoq#96]
I'm aware that the primitive operations are not verified, but I believe that there are some bugs in the C code for the Coq primitive `Uint63` operations (in `plugin/runtime/prim_int63.c`)

The specification for `Uint63.div x y ` defines the result to be 0 if the `y` is 0 (and this is also the result of  evaluating the expression in Coq with e.g. `Compute`). 
Currently the function `prim_int63_div` doesn't check the value of `y`, leading to a division-by-zero/ segfault if `y` is 0.

Similarly, the specification for `Uint63.mod x y` defines the result to be `x` if the `y` is zero, but `prim_int63_mod` doesn't check the value of `y`, and so also segfaults if it is 0. 

The above also has implications for `Uint63.diveucl x y`. It's defined to return `(Uint63.div x y, Uint63.mod x y)`, but the function `prim_int63_diveucl` returns `(0, 0)` for inputs `x` and `y` if `y` is 0 while it should be `(0, x)`.

The specification for logical shifts `Uint63.lsl x y` and `Uint63.lsr x  y` implies that the result is 0 if  `63 <= y ` (and this is also the actual result of evaluating such an expression), but in C the expressions `x << y` and `x >> y` have undefined behavior if `64 <= y`. 
For example, the result of `Compute Uint63.lsl 1 64.` is 0, but using CertiCoq to compile the expression to C and then compiling it with both `clang` (v 17.0.6), `gcc` (v 13.2.1) and `ccomp` (v 3.12) and then pretty printing the resulting value (I used the function `Unsigned_long_val` in `plugin/runtime/values.h` on the  value I get back from the main/ body function and then did `printf("%llu\n", x)`) gives me 1. 
The story is similar for right shift. 

Finally, I think there is a mistake in the implementation of `Uint63.mulc`. 

First, I think some of the expressions in `mulc_aux` should be taken modulo 2^63 (it seems like the C code is translated from the `ml` code in the Coq kernel,  which assumes 63-bit integers).

For instance,  I think the statement `l = (l + hl2);` on line 292 should be `l = (l + hl2) & maxuint63;`, because `l` is used in a comparison on the next line to check for a carry, which could get lost if the result of the addition is greater than 2^63-1 but not greater than 2^64-1. 
For example, the result of `Compute Uint63.mulc 12188099900 12188099900.` is `(16, 975826582703597072)`, but using CertiCoq to compile the expression to C and pretty print the result with glue code for `prod` gives me `(pair 15 975826582703597072)`. 
It  should probably also be done  for the statement `unsigned long long hl = hxly + lxhy;` on line 289,  since `hl` is also used in the next line to check for a carry. 

Secondly, I think there is a dereference missing in the else branch in `prim_int63_mulc`, when extracting the arguments from the pair, line 308 and 309, I believe it should be
``` C
unsigned long long h = Unsigned_long_val(*((unsigned long long*) p + 0));
unsigned long long l = Unsigned_long_val(*((unsigned long long*) p + 1));
```
Without the above dereference, the result of e.g. `Compute Uint63.mulc 8500964271916320249 8500964271916320249` is `(7835138088720211561, 6616587037742705713)`, but using CertiCoq to compile and run with pretty printing as above gives me different results on each execution.

**Comment by mattam82** [comment]
Thanks for the detailed report, indeed we did not verify or even stress test this at all yet. I implemented it by taking inspiration from the Coq kernel implementation but might have missed many things!

**Comment by mattam82** [comment]
@mkarup I tried to implement your suggested fixes, indeed the C code I wrote departs quite a bit from the ml code in Coq's kernel. Could you give it a review (and potentially a test?)

**Comment by mattam82** [comment]
@andrew-appel how hard would it be to simply verify this using VST?

**Comment by andrew-appel** [comment]
> @andrew-appel how hard would it be to simply verify this using VST?

This is a guide to how it would be done:
https://github.com/CertiCoq/VeriFFI/blob/main/doc/veriffi_techreport.pdf

**Comment by mkarup** [comment]
> @mkarup I tried to implement your suggested fixes, indeed the C code I wrote departs quite a bit from the ml code in Coq's kernel. Could you give it a review (and potentially a test?)

Apologies for the delayed reply. Thank you for looking into it. I have been a little busy lately, but I will set up and run the tests as soon as I have a free spot.

**Comment by mkarup** [comment]
The PR fixes the issues I reported, but of course the tests are by non means exhaustive (insert Dijkstra quote here).

One more thing that I forgot to add to the initial bug report:
Due to the left/ right shift issue, the implementation of `addmuldiv` also needs to be fixed.
If the first argument is greater than 63, then I *think* the result is always 0 (if the specification axioms for the primitives are to be consistent), but as I've recently learned, the story is [a little more complicated](https://github.com/coq/coq/issues/19402). 

For example, `Eval cbn in addmuldiv 64 42 42` gives 0, but compiling and executing the code extracted with CertiCoq gives 42.
However, `Compute addmuldiv 64 42 42` also gives 42, as described in the linked issue, which may or may not turn out to be the expected behavior, depending on how that issue shakes out.

If 0 is the correct result, then a fix could be to just add a guard to `addmuldiv`:
``` C
primint prim_int63_addmuldiv(primint pp, primint xp, primint yp)
{
  trace("Calling prim_int63_addmuldiv\n");
  unsigned long long p = Unsigned_long_val(pp);
  unsigned long long x = Unsigned_long_val(xp);
  unsigned long long y = Unsigned_long_val(yp);
  if (63 <= p) return Val_long(0);
  else {
    unsigned long long r = ((x << p) & maxuint63) | y >> (uint_size - p);
    trace("Calling addmuldiv with %llu, %llu and %llu: %llu\n", p, x, y, r);
    return Val_long(r);
  }
}
```

**Comment by mkarup** [comment]
Sorry, one more thing that I didn't spot when I tested the fix: 

`diveucl` is defined as  `diveucl x y = (x / y, x mod y)`, so  I think `diveucl x 0` should return `(0, x)`: 
``` C
primintpair prim_int63_diveucl(struct thread_info *ti, primint xp, primint yp)
{
  unsigned long long x = Unsigned_long_val(xp);
  unsigned long long y = Unsigned_long_val(yp);
  trace("Calling prim_int63_diveucl\n");
  if (y == 0) return (mk_pair (ti, Val_long(0), Val_long(x)));
  else 
    return (mk_pair (ti, Val_long(x / y), Val_long(x % y)));
}
```

**Comment by mattam82** [comment]
Now merged.
